/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wcq.ramp.up;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        int[] numbers = {8, 12, 16};
        int gcd = GCDEuclideanAlg.findGCD(numbers);
        System.out.println("GCD of " + Arrays.toString(numbers) + " is: " + gcd);
    }
}
