/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wcq.ramp.up;

// New class GCDEuc... to parse through App.java
public class GCDEuclideanAlg {
    /**
     * @param nums
     * @return
     */
    public static int findGCD(int[] nums) {
        if (nums.length == 0) {
            return 0;
        }
        // Matching the GCD array provided with the result given
        int result = nums[0];
        for (int num : nums) {
            result = gcd(result, num);
        }

        return result;
    }

    private static int gcd(int a, int b) {
        while (b != 0) {
            int temp = b;
            b = a % b;
            a = temp;
        }
        return a;
    }

}